# Generated by Django 3.2.7 on 2021-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='ID врача')),
                ('username', models.CharField(max_length=50, verbose_name='Имя врача')),
                ('specialization', models.CharField(max_length=60, verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='1', max_length=20, verbose_name='ID пользователя')),
                ('order_id', models.CharField(max_length=100, verbose_name='ID заявки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
    ]
