# Generated by Django 3.2.7 on 2021-09-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_accept',
            field=models.BooleanField(default='False', verbose_name='Найден врач'),
        ),
    ]
