# Generated by Django 3.2.7 on 2021-09-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ready',
            field=models.BooleanField(default='False', verbose_name='Выполнена'),
        ),
    ]
